name: moneyapp
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  get: ^4.6.5
  flutter_svg: ^1.1.0
  freezed_annotation: ^2.0.3
  intl: ^0.17.0
  uuid: ^3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.1.11
  flutter_lints: ^2.0.0
  freezed: ^2.0.3

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
